

export enum UserRole {
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
  VENDOR = "VENDOR",
  CUSTOMER = "CUSTOMER",
  STAFF = "STAFF"
}

export enum BookingStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CHECKED_IN = "CHECKED_IN",
  CHECKED_OUT = "CHECKED_OUT",
  CANCELLED = "CANCELLED",
  CANCELLATION_REQUESTED = "CANCELLATION_REQUESTED",
  NO_SHOW = "NO_SHOW"
}

export enum PaymentStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED"
}

export enum PaymentMethod {
  CREDIT_CARD = "CREDIT_CARD",
  PAYPAL = "PAYPAL",
  BANK_TRANSFER = "BANK_TRANSFER",
  CASH = "CASH",
  PAYSTACK = "PAYSTACK",
  FLUTTERWAVE = "FLUTTERWAVE"
}

export enum TaskStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  ON_HOLD = "ON_HOLD",
  CANCELLED = "CANCELLED"
}

export enum TaskPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
  EMERGENCY = "EMERGENCY"
}

export enum TaskCategory {
  CLEANING = "CLEANING",
  REPAIR = "REPAIR",
  INSPECTION = "INSPECTION",
  REPLACEMENT = "REPLACEMENT",
  PREVENTIVE= "PREVENTIVE",
  GUEST_REQUEST = "GUEST_REQUEST",
  IT_SUPPORT = "IT_SUPPORT",
  PLUMBING = "PLUMBING",
  ELECTRICAL = "ELECTRICAL",
  HVAC = "HVAC",
  GENERAL= "GENERAL"
}

export enum MaintenanceType {
  CORRECTIVE = "CORRECTIVE",
  PREVENTIVE = "PREVENTIVE",
  PREDICTIVE = "PREDICTIVE",
  EMERGENCY = "EMERGENCY",
  OTHER = "OTHER"
}

export enum ModuleType {
  WIFI = "WIFI",
  KEYCARD = "KEYCARD",
  CCTV = "CCTV",
  MENU = "MENU",
  LOCK = "LOCK",
  MAINTENANCE = "MAINTENANCE",
  ANALYTICS = "ANALYTICS",
  FACILITY_MANAGEMENT = "FACILITY_MANAGEMENT"
}

export enum NotificationType {
  SYSTEM = "SYSTEM",
  BOOKING = "BOOKING",
  PAYMENT = "PAYMENT",
  MAINTENANCE = "MAINTENANCE",
  PROMOTION = "PROMOTION",
  SUBSCRIPTION = "SUBSCRIPTION",
  MESSAGE = "MESSAGE",
  ANNOUNCEMENT = "ANNOUNCEMENT",
  OTHER = "OTHER"
}

export enum NotificationStatus {
  UNREAD = "UNREAD",
  READ = "READ",
  ARCHIVED = "ARCHIVED"
}

export enum NotificationRecipient {
  ALL = "ALL",
  ADMINS = "ADMINS",
  VENDORS = "VENDORS",
  CUSTOMERS = "CUSTOMERS",
  STAFF = "STAFF"
}

export enum SubscriptionPlan {
  FREE = "FREE",
  BASIC = "BASIC",
  STANDARD = "STANDARD",
  PREMIUM = "PREMIUM"
} 